[book]
authors = ["Fabian Hirschmann"]
language = "en"
multilingual = false
src = "docs"
extra-watch-dirs = ["docs"]
title = "Data & AI Bootkon Handbook"

[build]
build-dir = "output"

[output.html]
additional-css = ["docs/css/alerts.css", "docs/css/custom.css"]
default-theme = "navy"
smart-punctuation = true
git-repository-url = "https://github.com/fhirschmann/bootkon"

[preprocessor.cloud_shell]
command = "./.scripts/bk-render-neos"

[preprocessor.jinja2]
command = "./.scripts/bk-render-jinja2"
