[book]
authors = ["Fabian Hirschmann"]
language = "en"
multilingual = false
src = "docs"
extra-watch-dirs = ["docs"]
title = "Bootkon Handbook"

[preprocessor.cloud_shell]
command = "python3 docs/scripts/mdbook_preprocessor_cloudshell.py"

[preprocessor.jinja2]
command = "python3 docs/scripts/mdbook_preprocessor_jinja2.py"