name: Concatenate Files

on:
  push:
    branches:
      - main

jobs:
  concatenate-files:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Concatenate all files in "labs" directory
        run: |
          # Ensure the output file doesn't already exist
          rm -f .TUTORIAL.md
          # Concatenate all files
          cat labs/* > .TUTORIAL.md
      - name: Push to GitHub
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Create Cloud Shell tutorial .TUTORIAL.md
          file_pattern: '.TUTORIAL.md'


